<?php

class Tyrion extends Lannister {

    public function __construct() {
        parent::__construct();
        print ("My name is Tyrion" . PHP_EOL);
        return;
    }

    public function getSize()
    {
        return "Short";
    }

    public function houseMotto()
    {
        return parent::houseMotto(); // TODO: Change the autogenerated stub
    }
}

?>